[supervisord]
nodaemon=true
logfile=/var/www/micrologs/logs/supervisord.log

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:micrologs-pageview]
command=php /var/www/micrologs/workers/pageview-worker.php
directory=/var/www/micrologs
autostart=true
autorestart=true
startretries=5
numprocs=3
process_name=%(program_name)s_%(process_num)02d
pidfile=/var/www/micrologs/supervisor/pids/%(program_name)s_%(process_num)02d.pid
stdout_logfile=/var/www/micrologs/logs/pageview-worker.log
stderr_logfile=/var/www/micrologs/logs/pageview-worker-error.log
user=www-data

[program:micrologs-error]
command=php /var/www/micrologs/workers/error-worker.php
directory=/var/www/micrologs
autostart=true
autorestart=true
startretries=5
numprocs=2
process_name=%(program_name)s_%(process_num)02d
pidfile=/var/www/micrologs/supervisor/pids/%(program_name)s_%(process_num)02d.pid
stdout_logfile=/var/www/micrologs/logs/error-worker.log
stderr_logfile=/var/www/micrologs/logs/error-worker-error.log
user=www-data

[program:micrologs-audit]
command=php /var/www/micrologs/workers/audit-worker.php
directory=/var/www/micrologs
autostart=true
autorestart=true
startretries=5
numprocs=2
process_name=%(program_name)s_%(process_num)02d
pidfile=/var/www/micrologs/supervisor/pids/%(program_name)s_%(process_num)02d.pid
stdout_logfile=/var/www/micrologs/logs/audit-worker.log
stderr_logfile=/var/www/micrologs/logs/audit-worker-error.log
user=www-data